/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Spam.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Spam.Model
{
    /// <summary>
    /// SpamDetectionAdvancedResponse
    /// </summary>
    [DataContract]
    public partial class SpamDetectionAdvancedResponse :  IEquatable<SpamDetectionAdvancedResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">cleanResult.</param>
        public SpamDetectionAdvancedResponse(bool? cleanResult = default(bool?))
        {
            this.CleanResult = cleanResult;
        }
        
        /// <summary>
        /// Gets or Sets CleanResult
        /// </summary>
        [DataMember(Name="cleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpamDetectionAdvancedResponse);
        }

        /// <summary>
        /// Returns true if SpamDetectionAdvancedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SpamDetectionAdvancedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpamDetectionAdvancedResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                return hashCode;
            }
        }
    }

}
