/* 
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Spam.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Spam.Model
{
    /// <summary>
    /// Form field submitted to run spam detection on
    /// </summary>
    [DataContract]
    public partial class SpamDetectionAdvancedFormField :  IEquatable<SpamDetectionAdvancedFormField>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedFormField" /> class.
        /// </summary>
        /// <param name="fieldTitle">Title of the field.</param>
        /// <param name="fieldValue">Value of the field.</param>
        public SpamDetectionAdvancedFormField(string fieldTitle = default(string), string fieldValue = default(string))
        {
            this.FieldTitle = fieldTitle;
            this.FieldValue = fieldValue;
        }
        
        /// <summary>
        /// Title of the field
        /// </summary>
        /// <value>Title of the field</value>
        [DataMember(Name="FieldTitle", EmitDefaultValue=false)]
        public string FieldTitle { get; set; }

        /// <summary>
        /// Value of the field
        /// </summary>
        /// <value>Value of the field</value>
        [DataMember(Name="FieldValue", EmitDefaultValue=false)]
        public string FieldValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedFormField {\n");
            sb.Append("  FieldTitle: ").Append(FieldTitle).Append("\n");
            sb.Append("  FieldValue: ").Append(FieldValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpamDetectionAdvancedFormField);
        }

        /// <summary>
        /// Returns true if SpamDetectionAdvancedFormField instances are equal
        /// </summary>
        /// <param name="input">Instance of SpamDetectionAdvancedFormField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpamDetectionAdvancedFormField input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FieldTitle == input.FieldTitle ||
                    (this.FieldTitle != null &&
                    this.FieldTitle.Equals(input.FieldTitle))
                ) && 
                (
                    this.FieldValue == input.FieldValue ||
                    (this.FieldValue != null &&
                    this.FieldValue.Equals(input.FieldValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FieldTitle != null)
                    hashCode = hashCode * 59 + this.FieldTitle.GetHashCode();
                if (this.FieldValue != null)
                    hashCode = hashCode * 59 + this.FieldValue.GetHashCode();
                return hashCode;
            }
        }
    }

}
