/* 
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Spam.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Spam.Model
{
    /// <summary>
    /// AI advanced spam detection request
    /// </summary>
    [DataContract]
    public partial class SpamDetectionAdvancedRequest :  IEquatable<SpamDetectionAdvancedRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedRequest" /> class.
        /// </summary>
        /// <param name="inputString">Input text string to detect spam against.</param>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced..</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise.</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise.</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise.</param>
        public SpamDetectionAdvancedRequest(string inputString = default(string), string model = default(string), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), bool? allowPhishing = default(bool?))
        {
            this.InputString = inputString;
            this.Model = model;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowPhishing = allowPhishing;
        }
        
        /// <summary>
        /// Input text string to detect spam against
        /// </summary>
        /// <value>Input text string to detect spam against</value>
        [DataMember(Name="InputString", EmitDefaultValue=false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
        /// </summary>
        /// <value>Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.</value>
        [DataMember(Name="Model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// True if unsolicited sales should be allowed, false otherwise
        /// </summary>
        /// <value>True if unsolicited sales should be allowed, false otherwise</value>
        [DataMember(Name="AllowUnsolicitedSales", EmitDefaultValue=false)]
        public bool? AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// True if promotional content should be allowed, false otherwise
        /// </summary>
        /// <value>True if promotional content should be allowed, false otherwise</value>
        [DataMember(Name="AllowPromotionalContent", EmitDefaultValue=false)]
        public bool? AllowPromotionalContent { get; set; }

        /// <summary>
        /// True if phishing should be allowed, false otherwise
        /// </summary>
        /// <value>True if phishing should be allowed, false otherwise</value>
        [DataMember(Name="AllowPhishing", EmitDefaultValue=false)]
        public bool? AllowPhishing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedRequest {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowPhishing: ").Append(AllowPhishing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpamDetectionAdvancedRequest);
        }

        /// <summary>
        /// Returns true if SpamDetectionAdvancedRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SpamDetectionAdvancedRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpamDetectionAdvancedRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputString == input.InputString ||
                    (this.InputString != null &&
                    this.InputString.Equals(input.InputString))
                ) && 
                (
                    this.Model == input.Model ||
                    (this.Model != null &&
                    this.Model.Equals(input.Model))
                ) && 
                (
                    this.AllowUnsolicitedSales == input.AllowUnsolicitedSales ||
                    (this.AllowUnsolicitedSales != null &&
                    this.AllowUnsolicitedSales.Equals(input.AllowUnsolicitedSales))
                ) && 
                (
                    this.AllowPromotionalContent == input.AllowPromotionalContent ||
                    (this.AllowPromotionalContent != null &&
                    this.AllowPromotionalContent.Equals(input.AllowPromotionalContent))
                ) && 
                (
                    this.AllowPhishing == input.AllowPhishing ||
                    (this.AllowPhishing != null &&
                    this.AllowPhishing.Equals(input.AllowPhishing))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputString != null)
                    hashCode = hashCode * 59 + this.InputString.GetHashCode();
                if (this.Model != null)
                    hashCode = hashCode * 59 + this.Model.GetHashCode();
                if (this.AllowUnsolicitedSales != null)
                    hashCode = hashCode * 59 + this.AllowUnsolicitedSales.GetHashCode();
                if (this.AllowPromotionalContent != null)
                    hashCode = hashCode * 59 + this.AllowPromotionalContent.GetHashCode();
                if (this.AllowPhishing != null)
                    hashCode = hashCode * 59 + this.AllowPhishing.GetHashCode();
                return hashCode;
            }
        }
    }

}
