/* 
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Spam.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Spam.Model
{
    /// <summary>
    /// AI spam detection request
    /// </summary>
    [DataContract]
    public partial class SpamDetectionRequest :  IEquatable<SpamDetectionRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionRequest" /> class.
        /// </summary>
        /// <param name="inputString">Input text string to detect spam against.</param>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced..</param>
        public SpamDetectionRequest(string inputString = default(string), string model = default(string))
        {
            this.InputString = inputString;
            this.Model = model;
        }
        
        /// <summary>
        /// Input text string to detect spam against
        /// </summary>
        /// <value>Input text string to detect spam against</value>
        [DataMember(Name="InputString", EmitDefaultValue=false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
        /// </summary>
        /// <value>Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.</value>
        [DataMember(Name="Model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpamDetectionRequest {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpamDetectionRequest);
        }

        /// <summary>
        /// Returns true if SpamDetectionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SpamDetectionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpamDetectionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputString == input.InputString ||
                    (this.InputString != null &&
                    this.InputString.Equals(input.InputString))
                ) && 
                (
                    this.Model == input.Model ||
                    (this.Model != null &&
                    this.Model.Equals(input.Model))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputString != null)
                    hashCode = hashCode * 59 + this.InputString.GetHashCode();
                if (this.Model != null)
                    hashCode = hashCode * 59 + this.Model.GetHashCode();
                return hashCode;
            }
        }
    }

}
