/* 
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.Spam.Client;
using Cloudmersive.APIClient.NETCore.Spam.Model;

namespace Cloudmersive.APIClient.NETCore.Spam.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpamDetectionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        SpamDetectionAdvancedResponse SpamDetectFileAdvancedPost (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        ApiResponse<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostWithHttpInfo (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        SpamDetectionResponse SpamDetectFilePost (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        ApiResponse<SpamDetectionResponse> SpamDetectFilePostWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionFormSubmissionAdvancedResponse</returns>
        SpamDetectionFormSubmissionAdvancedResponse SpamDetectFormSubmissionAdvancedPost (SpamDetectionAdvancedFormSubmissionRequest body = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionFormSubmissionAdvancedResponse</returns>
        ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostWithHttpInfo (SpamDetectionAdvancedFormSubmissionRequest body = null);
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        SpamDetectionAdvancedResponse SpamDetectTextStringAdvancedPost (SpamDetectionAdvancedRequest body = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        ApiResponse<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostWithHttpInfo (SpamDetectionAdvancedRequest body = null);
        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        SpamDetectionResponse SpamDetectTextStringPost (SpamDetectionRequest body = null);

        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        ApiResponse<SpamDetectionResponse> SpamDetectTextStringPostWithHttpInfo (SpamDetectionRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostAsync (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectFileAdvancedPostAsyncWithHttpInfo (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectFilePostAsync (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectFilePostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionFormSubmissionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostAsync (SpamDetectionAdvancedFormSubmissionRequest body = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionFormSubmissionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>> SpamDetectFormSubmissionAdvancedPostAsyncWithHttpInfo (SpamDetectionAdvancedFormSubmissionRequest body = null);
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostAsync (SpamDetectionAdvancedRequest body = null);

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectTextStringAdvancedPostAsyncWithHttpInfo (SpamDetectionAdvancedRequest body = null);
        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectTextStringPostAsync (SpamDetectionRequest body = null);

        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectTextStringPostAsyncWithHttpInfo (SpamDetectionRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SpamDetectionApi : ISpamDetectionApi
    {
        private Cloudmersive.APIClient.NETCore.Spam.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SpamDetectionApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.Spam.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SpamDetectionApi(Cloudmersive.APIClient.NETCore.Spam.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.Spam.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.Spam.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.Spam.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        public SpamDetectionAdvancedResponse SpamDetectFileAdvancedPost (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = SpamDetectFileAdvancedPostWithHttpInfo(model, preprocessing, allowPhishing, allowUnsolicitedSales, allowPromotionalContent, customPolicyId, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        public ApiResponse< SpamDetectionAdvancedResponse > SpamDetectFileAdvancedPostWithHttpInfo (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./spam/detect/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (preprocessing != null) localVarHeaderParams.Add("preprocessing", this.Configuration.ApiClient.ParameterToString(preprocessing)); // header parameter
            if (allowPhishing != null) localVarHeaderParams.Add("allowPhishing", this.Configuration.ApiClient.ParameterToString(allowPhishing)); // header parameter
            if (allowUnsolicitedSales != null) localVarHeaderParams.Add("allowUnsolicitedSales", this.Configuration.ApiClient.ParameterToString(allowUnsolicitedSales)); // header parameter
            if (allowPromotionalContent != null) localVarHeaderParams.Add("allowPromotionalContent", this.Configuration.ApiClient.ParameterToString(allowPromotionalContent)); // header parameter
            if (customPolicyId != null) localVarHeaderParams.Add("customPolicyId", this.Configuration.ApiClient.ParameterToString(customPolicyId)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostAsync (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = await SpamDetectFileAdvancedPostAsyncWithHttpInfo(model, preprocessing, allowPhishing, allowUnsolicitedSales, allowPromotionalContent, customPolicyId, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to Advanced)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to Auto)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectFileAdvancedPostAsyncWithHttpInfo (string model = null, string preprocessing = null, bool? allowPhishing = null, bool? allowUnsolicitedSales = null, bool? allowPromotionalContent = null, string customPolicyId = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./spam/detect/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (preprocessing != null) localVarHeaderParams.Add("preprocessing", this.Configuration.ApiClient.ParameterToString(preprocessing)); // header parameter
            if (allowPhishing != null) localVarHeaderParams.Add("allowPhishing", this.Configuration.ApiClient.ParameterToString(allowPhishing)); // header parameter
            if (allowUnsolicitedSales != null) localVarHeaderParams.Add("allowUnsolicitedSales", this.Configuration.ApiClient.ParameterToString(allowUnsolicitedSales)); // header parameter
            if (allowPromotionalContent != null) localVarHeaderParams.Add("allowPromotionalContent", this.Configuration.ApiClient.ParameterToString(allowPromotionalContent)); // header parameter
            if (customPolicyId != null) localVarHeaderParams.Add("customPolicyId", this.Configuration.ApiClient.ParameterToString(customPolicyId)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        public SpamDetectionResponse SpamDetectFilePost (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<SpamDetectionResponse> localVarResponse = SpamDetectFilePostWithHttpInfo(model, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        public ApiResponse< SpamDetectionResponse > SpamDetectFilePostWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./spam/detect/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionResponse)));
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectFilePostAsync (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<SpamDetectionResponse> localVarResponse = await SpamDetectFilePostAsyncWithHttpInfo(model, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectFilePostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./spam/detect/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionResponse)));
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionFormSubmissionAdvancedResponse</returns>
        public SpamDetectionFormSubmissionAdvancedResponse SpamDetectFormSubmissionAdvancedPost (SpamDetectionAdvancedFormSubmissionRequest body = null)
        {
             ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> localVarResponse = SpamDetectFormSubmissionAdvancedPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionFormSubmissionAdvancedResponse</returns>
        public ApiResponse< SpamDetectionFormSubmissionAdvancedResponse > SpamDetectFormSubmissionAdvancedPostWithHttpInfo (SpamDetectionAdvancedFormSubmissionRequest body = null)
        {

            var localVarPath = "./spam/detect/form-submission/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFormSubmissionAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionFormSubmissionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionFormSubmissionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionFormSubmissionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostAsync (SpamDetectionAdvancedFormSubmissionRequest body = null)
        {
             ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> localVarResponse = await SpamDetectFormSubmissionAdvancedPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionFormSubmissionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>> SpamDetectFormSubmissionAdvancedPostAsyncWithHttpInfo (SpamDetectionAdvancedFormSubmissionRequest body = null)
        {

            var localVarPath = "./spam/detect/form-submission/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectFormSubmissionAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionFormSubmissionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionFormSubmissionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        public SpamDetectionAdvancedResponse SpamDetectTextStringAdvancedPost (SpamDetectionAdvancedRequest body = null)
        {
             ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = SpamDetectTextStringAdvancedPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        public ApiResponse< SpamDetectionAdvancedResponse > SpamDetectTextStringAdvancedPostWithHttpInfo (SpamDetectionAdvancedRequest body = null)
        {

            var localVarPath = "./spam/detect/text-string/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectTextStringAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostAsync (SpamDetectionAdvancedRequest body = null)
        {
             ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = await SpamDetectTextStringAdvancedPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectTextStringAdvancedPostAsyncWithHttpInfo (SpamDetectionAdvancedRequest body = null)
        {

            var localVarPath = "./spam/detect/text-string/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectTextStringAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        public SpamDetectionResponse SpamDetectTextStringPost (SpamDetectionRequest body = null)
        {
             ApiResponse<SpamDetectionResponse> localVarResponse = SpamDetectTextStringPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        public ApiResponse< SpamDetectionResponse > SpamDetectTextStringPostWithHttpInfo (SpamDetectionRequest body = null)
        {

            var localVarPath = "./spam/detect/text-string";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectTextStringPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionResponse)));
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectTextStringPostAsync (SpamDetectionRequest body = null)
        {
             ApiResponse<SpamDetectionResponse> localVarResponse = await SpamDetectTextStringPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectTextStringPostAsyncWithHttpInfo (SpamDetectionRequest body = null)
        {

            var localVarPath = "./spam/detect/text-string";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpamDetectTextStringPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpamDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpamDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpamDetectionResponse)));
        }

    }
}
